SOURCE_CSV = "autogenerated_inductors.csv"
OUTPUT_FILE = (
    "C:\\Users\\Dan\\Documents\\kicad_wut\\kicad_libraries\\Inductor_Auto_WUT.kicad_sym"
)


def add_symbol(manufacturer, mpn, value, footprint, datasheet, tolerance, height):
    return f"""
  (symbol "{manufacturer} {mpn}" (extends "L")
    (property "Reference" "L" (at 2.54 2.54 0)
      (effects (font (size 1.27 1.27)) (justify left))
    )
    (property "Value" "{value}" (at 2.54 0 0)
      (effects (font (size 1.27 1.27)) (justify left))
    )
    (property "Footprint" "{footprint}" (at 0 0 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (property "Datasheet" "{datasheet}" (at 0 0 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (property "Manufacturer" "{manufacturer}" (at 0 0 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (property "MPN" "{mpn}" (at 0 0 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (property "Tolerance" "{tolerance}" (at 0 0 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (property "Height" "{height}mm" (at 0 0 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (property "ki_description" "{value} +-{tolerance} Inductor" (at 0 0 0)
      (effects (font (size 1.27 1.27)) hide)
    )
  )
"""


with open(SOURCE_CSV) as file, open(OUTPUT_FILE, "w+") as library:
    library.write(
        """(kicad_symbol_lib (version 20220914) (generator kicad_symbol_editor)
  (symbol "L" (pin_numbers hide) (pin_names hide) (in_bom yes) (on_board yes)
    (property "Reference" "L" (at -1.27 0 0)
      (effects (font (size 1.27 1.27)))
    )
    (property "Value" "" (at 2.54 0 0)
      (effects (font (size 1.27 1.27)))
    )
    (property "Footprint" "" (at 0 0 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (property "Datasheet" "" (at 0 0 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (symbol "L_0_1"
      (arc (start 0 -2.54) (mid 0.6323 -1.905) (end 0 -1.27)
        (stroke (width 0) (type default))
        (fill (type none))
      )
      (arc (start 0 -1.27) (mid 0.6323 -0.635) (end 0 0)
        (stroke (width 0) (type default))
        (fill (type none))
      )
      (arc (start 0 0) (mid 0.6323 0.635) (end 0 1.27)
        (stroke (width 0) (type default))
        (fill (type none))
      )
      (arc (start 0 1.27) (mid 0.6323 1.905) (end 0 2.54)
        (stroke (width 0) (type default))
        (fill (type none))
      )
    )
    (symbol "L_1_1"
      (pin passive line (at 0 3.81 270) (length 1.27)
        (name "1" (effects (font (size 1.27 1.27))))
        (number "1" (effects (font (size 1.27 1.27))))
      )
      (pin passive line (at 0 -3.81 90) (length 1.27)
        (name "2" (effects (font (size 1.27 1.27))))
        (number "2" (effects (font (size 1.27 1.27))))
      )
    )
  )
"""
    )

    file.readline()  # Remove headers
    for line in file:
        (
            manufacturer,
            mpn,
            value,
            footprint,
            height,
            tolerance,
            datasheet,
        ) = [x.strip() for x in line.split(",")]
        library.write(
            add_symbol(
                manufacturer=manufacturer,
                mpn=mpn,
                value=value,
                footprint=footprint,
                datasheet=datasheet,
                tolerance=tolerance,
                height=height,
            )
        )
    library.write(")")
